### ISSUE TITLE
Invalid characters when using the installer

### ISSUE THREAD

**Issue by k3mist** [jenskutilek/FiraSystemFontReplacement#48]
This is the dialog for entering your email and password for the App store. Also password boxes are broken where the character is invisible.

![screen shot 2017-09-02 at 6 31 26 pm](https://user-images.githubusercontent.com/439440/29999194-11f3a236-900d-11e7-97c7-f2adc58b3fa4.png)

**Comment by splorp** [comment]
What version of OS X/macOS are you running?

**Comment by k3mist** [comment]
Sierra

**Comment by splorp** [comment]
@k3mist Ok, but which version of Sierra? There have been issues when using the font on non-updated versions of Sierra. For example: #46

I’m running 10.12.6 and do not see this problem in the App Store.

**Comment by k3mist** [comment]
10.12.6 

![screen shot 2017-09-06 at 10 17 54 pm](https://user-images.githubusercontent.com/439440/30142967-6cad3bdc-9351-11e7-885d-328fccce66a5.png)

**Comment by k3mist** [comment]
The dialog was from an App that wanted me to authenticate with the App store, so that dialog was asking for my Apple email/password. I've switched back to the default fonts for now. I'll see about getting this to happen again so you can replicate it on your end.

However, in any "password" text box, it does not show the "•" character at all. This could be in any browser password text box, the OSX lock screen, etc.

**Comment by k3mist** [comment]
Hmm. The installer does not appear to install `FSDisplay.ttf`

Might this be the issue? Screenshot is from `/Library/Fonts`

<img width="202" alt="screen shot 2017-09-06 at 10 36 12 pm" src="https://user-images.githubusercontent.com/439440/30143518-30b5c8da-9354-11e7-9110-970250e62808.png">

**Comment by jenskutilek** [comment]
The FSDisplay.ttf font is not available yet, but that shouldn’t matter. The issue with the missing •••• in password fields has been fixed a while ago, could you try to install the [most recent release](https://github.com/jenskutilek/FiraSystemFontReplacement/releases/tag/v4.106.4) of the fonts?

**Comment by k3mist** [comment]
That fixed the password box issue. Still getting the same issue with some dialogs.

One example is from the app "Dash".  When I click purchase full version and I am not signed in to the App Store I get the invalid box characters. But App Store sign in from the App Store itself is good.

I was only able to duplicate it once from Dash at the moment. My internet right now is extremely shit from Hurricane Irma. Now I'm getting server errors saying it can't connect. I'll see if I can duplicate it again at some point. 

Going on no power and only internet via cell phone for 7 days and Verizon hasn't done anything to repair the Cell Towers it seems. (No neighboring cell towers according to hidden android menu)

Had to root my android so I could use it as a hotspot.

**Comment by k3mist** [comment]
Just noticed this in my network settings.

<img width="601" alt="screen shot 2017-09-20 at 8 43 24 pm" src="https://user-images.githubusercontent.com/439440/30673905-6a5d8230-9e44-11e7-9a0e-3d9cb08e9de7.png">

**Comment by SamusAranX** [comment]
This is still happening on 10.13.1.
![screen shot 2017-11-02 at 09 43 23](https://user-images.githubusercontent.com/676069/32316983-91cf877a-bfb2-11e7-9800-539b38cb0a18.png)
The password dots are displaying as question mark blocks, but I didn't get a screenshot of that.
I'm already using release v4.106.5.

**Comment by xujc** [comment]
This problem happens on my Mac (`MacBook Pro Retina, 13-inch, Late 2013, macOS High Sierra Version 10.13.2`)

<img width="692" alt="screen shot 2017-12-16 at 08 34 27" src="https://user-images.githubusercontent.com/7146271/34066440-b02a9660-e249-11e7-8547-466862876f57.png">

I have been using this Font replacement for about a month, and this is the only problem occurred to me (it is no big deal though).
